openapi: 3.0.1
info:
  title: Geocoding Enrichment
  description: Enriches the data that comes back from a geocoding response
  version: 1.0.2
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /process:
    post:
      operationId: process
      tags:
        - process
      summary: Process a response
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - requestId
                - chosenResultId
                - responseTime
                - geocodingResponse
              properties:
                requestId:
                  type: string
                chosenResultId:
                  type: number
                responseTime:
                  type: string
                  format: date-time
                geocodingResponse:
                  $ref: '#/components/schemas/geocodingResponse'
      responses:
        '200':
          description: processed
          content:
            application/json:
              schema:
                type: object
                required:
                  - user
                  - query
                  - result
                  - system
                  - site
                  - duration
                properties:
                  user:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                  query:
                    type: object
                    required:
                      - text
                      - language
                    properties:
                      text:
                        type: string
                      language:
                        type: string
                  result:
                    type: object
                    required:
                      - rank
                      - score
                      - source
                      - layer
                      - name
                    properties:
                      rank:
                        type: integer
                      score:
                        type: number
                      source:
                        type: string
                      layer:
                        type: string
                      name:
                        type: string
                  system:
                    type: string
                  site:
                    type: string
                  duration:
                    type: number
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  schemas:
    geocodingResponse:
      type: object
      required:
        - userId
        - apiKey
        - site
        - response
        - respondedAt
      properties:
        userId:
          type: string
        apiKey:
          type: string
        site:
          type: string
        respondedAt:
          type: string
          format: date-time
        geocodingResponse:
          type: object
          required:
            - type
            - features
            - geocoding
          properties:
            type:
              type: string
              enum:
                - FeatureCollection
            features:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - Feature
                  properties:
                    type: object
                    properties:
                      type:
                        type: string
                      source:
                        type: string
                      layer:
                        type: string
                      name:
                        type: object
                        properties:
                          default:
                            type: string
                      _score:
                        type: integer
            geocoding:
              type: object
              required:
                - query
                - response
              properties:
                version:
                  type: string
                  pattern: ^\d{3}\.\d{3}\.\d{3}$
                  example: 1.5.3
                query:
                  type: object
                  properties:
                    text:
                      type: string
                    limit:
                      type: integer
                    geo_context:
                      type: string
                    disable_fuzziness:
                      type: boolean
    errorSchema:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        status:
          type: number
  responses:
    BadRequest:
      description: Invalid Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorSchema'
    InternalError:
      description: Invalid Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorSchema'
