{{- $releaseName := .Release.Name -}}
{{- $chartName := include "geocoding-enrichment.name" . -}}
{{- $deploymentFlavor := include "geocoding-enrichment.deploymentFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "geocoding-enrichment.fullname" .) }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "geocoding-enrichment.environment" . }}
    release: {{ $releaseName }}
    {{- include "geocoding-enrichment.labels" . | nindent 4 }}
spec:
  {{- if eq $deploymentFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $deploymentFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "geocoding-enrichment.selectorLabels" . | nindent 4 }}
{{- end }}
