apiVersion: v2
name: geocoding-enrichment
description: A Helm chart for geocoding-enrichment service
type: application
version: 1.3.0
appVersion: 1.3.0
dependencies:
  - name: common
    repository: oci://acrarolibotnonprod.azurecr.io/helm
    version: 1.0.1
